src/Entity/Todo.php
<?php

namespace App\Entity;

use App\Repository\TodoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TodoRepository::class)
 */
class Todo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $priority;

    /**
     * @ORM\Column(type="datetime")
     */
    private $due_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPriority(): ?string
    {
        return $this->priority;
    }

    public function setPriority(string $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getDueDate(): ?\DateTimeInterface
    {
        return $this->due_date;
    }

    public function setDueDate(\DateTimeInterface $due_date): self
    {
        $this->due_date = $due_date;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }
}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use Symfony\Component\Form\Extension\Core\Type\TextType;

use Symfony\Component\Form\Extension\Core\Type\TextareaType;

use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Symfony\Component\HttpFoundation\Request;

use App\Entity\Todo;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class TodoController extends AbstractController
{
    # private $em = $this->getDoctrine()->getManager();

    
    /**
     * @Route("/", name="todo")
     */
    public function index(): Response
    {
        $todos = $this->getDoctrine()->getRepository(Todo::class)->findAll();
        # dd($todos);

        return $this->render('todo/index.html.twig', [
            "todos" => $todos
        ]);
    }

    /**
     * @Route("/create", name="todo_create")
     */
    public function createAction(Request $request): Response
    {
        $todo = new Todo;
        # dd($todo);
        
        $form = $this->createFormBuilder($todo)->add('name', TextType::class, array("attr"=>array("class"=>"form-control", "style"=>"margin-bottom:15px", "id"=>"demo")))
        ->add('category', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))

        ->add('description', TextareaType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))

        ->add('priority', ChoiceType::class, array('choices'=>array('Low'=>'Low', 'Normal'=>'Normal', 'High'=>'High' ),'attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))

        ->add('due_date', DateTimeType::class, array('attr' => array('style'=>'margin-bottom:15px')))

        ->add('save', SubmitType::class, array('label'=> 'Create Todo', 'attr' => array('class'=> 'btn-primary', 'style'=>'margin-bottom:15px')))

        ->getForm();

        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid()){
            # dd($request);
            $name = $form["name"]->getData();
            $category = $form['category']->getData();
            $description = $form['description']->getData();
            $priority = $form['priority']->getData();
            $due_date = $form['due_date']->getData();

            $now = new\DateTime('now');

            $todo->setName($name);
            $todo->setCategory($category);
            $todo->setDescription($description);

            $todo->setPriority($priority);

            $todo->setDueDate($due_date);

            $todo->setCreateDate($now);

            $em = $this->getDoctrine()->getManager();

            $em->persist($todo);
            $em->flush();
            $this->addFlash(
                "notice",
                "Todo Added to your database"
            );
            return $this->redirectToRoute("todo");
            # dd($now);
        }
        # <input name="name" type="text" class="form-control" style="margin-bottom:15px">
        return $this->render('todo/create.html.twig', [
            "form" => $form->createView()
        ]);
    }

    /**
     * @Route("/edit/{id}", name="todo_edit")
     */
    public function editAction($id, Request $request): Response
    {
        $todo = $this->getDoctrine()->getRepository('App:Todo')->find($id);
        # select * from todo where id = $_GET["id"]
        
        $now = new\DateTime('now');
    
         $form = $this->createFormBuilder($todo)->add('name', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-botton:15px')))
            ->add('category', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))
            ->add('description', TextareaType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-botton:15px')))
            ->add('priority', ChoiceType::class, array('choices'=>array('Low'=>'Low', 'Normal'=>'Normal', 'High'=>'High'),'attr' => array('class'=> 'form-control', 'style'=>'margin-botton:15px')))
             ->add('due_date', DateTimeType::class, array('attr' => array('style'=>'margin-bottom:15px')))
             ->add('save', SubmitType::class, array('label'=> 'Update Todo', 'attr' => array('class'=> 'btn-primary', 'style'=>'margin-botton:15px')))
             ->getForm();
        $form->handleRequest($request);
 
 
        if($form->isSubmitted() && $form->isValid()){
            //fetching data
            $name = $form['name']->getData();
            $category = $form['category']->getData();
            $description = $form['description']->getData();
            $priority = $form['priority']->getData();
            $due_date = $form['due_date']->getData();
            $now = new\DateTime('now');
            $em = $this->getDoctrine()->getManager();
            $todo->setName($name);
            $todo->setCategory($category);
            $todo->setDescription($description);
            $todo->setPriority($priority);
            $todo->setDueDate($due_date);
            $todo->setCreateDate($now);
            #$em->persist($todo);
            $em->flush();
            $this->addFlash(
                    'notice',
                    'Todo Updated'
                    );
            return $this->redirectToRoute('todo');
        }
        return $this->render('todo/edit.html.twig', array('todo' => $todo, 'form' => $form->createView())); 
    }

    /**
     * @Route("/details/{id}", name="todo_details")
     */
    public function detailsAction($id): Response
    {
        return $this->render('todo/details.html.twig', [
            
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
           <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

            <a class="navbar-brand" href="/">Navbar</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

                <span class="navbar-toggler-icon"></span>

            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav mr-auto">

                    <li class="nav-item active">

                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>

                    </li>

                    <li class="nav-item">

                        <a class="nav-link" href="/create">Create Todo</a>

                    </li>

                </ul>

            </div>

        </nav>

        {% for message in app.flashes('notice') %}

            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        {% block body %}{% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    </body>
</html>

templates/todo/create.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<h2 class="page-header">Add Todo</h2>

    {{form_start(form)}} 

    {{form_widget(form)}} 

    {{form_end(form)}}


{% endblock %}

templates/todo/details.html.twig
{% extends 'base.html.twig' %}


{% block body %}
details
{% endblock %}

templates/todo/edit.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<h2 class="page-header">Edit Todo</h2>

    {{form_start(form)}}

    {{form_widget(form)}}

    {{form_end(form)}}
{% endblock %}

templates/todo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TodoController!{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        {% for todo in todos %}
        <div class="col-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ todo.name }}</h5>
                    <p class="card-text">{{ todo.dueDate|date('F j, Y, g:i a') }}</p>
                    <a href="/edit/{{ todo.id }}" class="btn btn-primary">Edit</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}